# Generated by Django 5.1.1 on 2024-10-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongDB',
            new_name='Record',
        ),
    ]
