# Generated by Django 5.1.1 on 2024-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_rename_songdb_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='song_type',
            field=models.CharField(choices=[('Praise', 'praise'), ('Worship', 'worship')], max_length=50),
        ),
    ]
